server.port=8081
spring.application.name=app
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Curso;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=EnolaGay.255
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.redis.database=0
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=
spring.redis.timeout=60000