CREATE TABLE CUSTOMERS (CUSTOMER_NUMBER VARCHAR(8), PASSWORD VARCHAR(8), EMAIL VARCHAR(50), STATUS VARCHAR(1), CREATION VARCHAR(10), PRIMARY KEY (CUSTOMER_NUMBER));
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000001', 'password', 'ismadx821@proton.me', 'A', '2025-06-01');
INSERT INTO CUSTOMERS (CUSTOMER_NUMBER, PASSWORD, EMAIL, STATUS, CREATION) VALUES ('00000002', 'pass', 'ismadx821@hotmail.com', 'B', '2025-06-01');
